# # A tiny grid interface for Geomorphometry — v2
#
# Second iteration of `grid_interface_poc.jl`, implementing the decisions in
# `docs/src/grid-interface-decisions.md`:
#
# - the grid carries a GeometryOpsCore manifold (dispatch) and the raw CRS
#   (inert, for output rebuild); geometry queries take the grid alone
# - nodata "Option A": out-of-bounds is filtered by index against the valid
#   range with an isbits padval; interior nodata stays the kernel's business
# - per-neighbor geometry is hoisted once per call via `neighborgeometry`,
#   at the coarsest granularity at which it is invariant
# - `cellarea(grid)` (bulk, granularity-typed) and `cellarea(grid, I)`
# - a closed resolver kwarg set split by `splitspatial`; façades generated by
#   an `@eval` loop that also rebuilds output metadata
# - verbs are the API: `mapneighbors` (records), `mapwindow` (named north-up
#   window, rectilinear-only), and the bare `eachneighbor` loop (traversals)
# - estimators dispatch by method: Horn is window-only, PlaneFit is
#   grid-agnostic, `defaultmethod(f, grid)` picks per backend
# - `NeighborRings` holds its ring count as a plain field

using Rasters
import DiscreteGlobalGrids as DGG
import Stencils
import GeoFormatTypes
using GeoFormatTypes: EPSG
using GeometryOpsCore: Manifold, Planar, Spherical, Geodesic

const AUTHALIC_RADIUS_M = 6_371_007.180918475

# ## Grid objects
#
# `P == (xaxis, yaxis)`.  The coordinate payload is a semantic `(x, y)` tuple:
# Raster lookups for a Raster and ordinary axes for a raw matrix.  DD
# dimensions are only adapter inputs; they are not part of the grid algorithms
# receive.
#
# The manifold is the dispatch axis: it decides at compile time whether
# geometry is constant (`Planar`) or varies by latitude (`Spherical`).  The
# CRS is inert data, parsed exactly once in `spatialparts` and carried only so
# the output boundary can rebuild Raster metadata.

abstract type AbstractGridSpec end # no relation to DiscreteGlobalGrids.AbstractGrid ;)

struct RectilinearGrid{M<:Manifold,P,L,S,C} <: AbstractGridSpec
    manifold::M
    lookups::L
    spacing::S # signed semantic (x, y) spacing
    crs::C     # opaque; never dispatched on
end

function RectilinearGrid(manifold::Manifold, P::Tuple{Int,Int}, lookups, spacing, crs)
    P in ((1, 2), (2, 1)) || throw(ArgumentError("invalid axis map $P"))
    all(!iszero, spacing) || throw(ArgumentError("cell spacing must be nonzero"))
    manifold isa Geodesic && throw(ArgumentError(
        "Geodesic manifolds are not supported yet; use Spherical (authalic radius)"))
    return RectilinearGrid{typeof(manifold),P,typeof(lookups),typeof(spacing),typeof(crs)}(
        manifold, lookups, spacing, crs)
end

axismap(::RectilinearGrid{M,P}) where {M,P} = P
yaxisnum(grid::RectilinearGrid) = axismap(grid)[2]

function gridsize(grid::RectilinearGrid)
    nx, ny = length(grid.lookups[1]), length(grid.lookups[2])
    return ntuple(axis -> axis == axismap(grid)[1] ? nx : ny, 2)
end

manifold(grid::RectilinearGrid) = grid.manifold

# A cell grid retains the cell collection needed to ask DGG about topology and
# geometry.  It needs no manifold field: a DGG level grid is inherently
# spherical.

struct CellGrid{C,G} <: AbstractGridSpec
    cells::C
    levelgrid::G
end

function CellGrid(celldim)
    lookup = Rasters.lookup(celldim)
    lookup isa DGG.CellLookup ||
        throw(ArgumentError("Dimension must contain a DGG.CellLookup; found $(typeof(lookup))"))
    cells = lookup.cells
    levelgrid = DGG.levelgrid(DGG.system(cells), DGG.level(cells))
    return CellGrid{typeof(cells),typeof(levelgrid)}(cells, levelgrid)
end

manifold(::CellGrid) = Spherical(; radius=AUTHALIC_RADIUS_M)

# ## Adapters
#
# A matrix has the package's existing convention: axis 1 is X and axis 2 is Y,
# and no CRS means planar geometry — the package's old implicit assumption,
# now stated on the grid.

function spatialparts(A::AbstractMatrix; spatialdims=nothing, spacing=nothing, manifold=nothing)
    isnothing(spatialdims) || spatialdims == (1, 2) ||
        throw(ArgumentError("a matrix uses spatialdims=(1, 2)"))
    steps = isnothing(spacing) ? (1.0, 1.0) : spacing
    m = isnothing(manifold) ? Planar() : manifold
    grid = RectilinearGrid(m, (1, 2), axes(A), steps, nothing)
    return A, grid
end

isspatialdim(::Type) = false
isspatialdim(::Type{<:Rasters.XDim}) = true
isspatialdim(::Type{<:Rasters.YDim}) = true
isspatialdim(::Type{<:DGG.Cells}) = true

_astuple(x::Tuple) = x
_astuple(x) = (x,)

# Placeholder CRS oracle.  The real version belongs next to the CRS machinery
# in the Rasters extension; the boundary contract is only that the conclusion
# is drawn once, here, and stored as the manifold.
_isgeographiccrs(::Nothing) = false
_isgeographiccrs(crs::EPSG) = GeoFormatTypes.val(crs) == 4326
_isgeographiccrs(crs) = occursin(r"GEOGCS|GEOGCRS"i, string(GeoFormatTypes.val(crs)))

function spatialparts(r::Raster; spatialdims=nothing, spacing=nothing, manifold=nothing)
    found_spatialdims = if isnothing(spatialdims)
        filter(d -> isspatialdim(typeof(d)), Rasters.dims(r))
    else
        Rasters.dims(r, spatialdims)
    end
    selected = _astuple(found_spatialdims)

    if length(selected) == 1 && lookup(only(selected)) isa DGG.CellLookup
        ndims(r) == 1 || throw(ArgumentError("Cells must be the only array axis"))
        isnothing(spacing) || throw(ArgumentError("CellGrid derives geometry from DGG"))
        isnothing(manifold) ||
            throw(ArgumentError("a CellGrid's manifold is fixed by its DGG system"))
        return r, CellGrid(only(selected))
    end

    ndims(r) == 2 || throw(ArgumentError("a rectilinear surface must be 2D"))
    length(selected) == 2 ||
        throw(ArgumentError("expected one X and one Y dimension, or one Cells dimension"))

    xdim = only(filter(d -> d isa Rasters.XDim, selected))
    ydim = only(filter(d -> d isa Rasters.YDim, selected))
    P = Rasters.dimnum(r, (Rasters.XDim, Rasters.YDim))
    lookups = (Rasters.lookup(xdim), Rasters.lookup(ydim))
    steps = isnothing(spacing) ? (Float64(step(xdim)), Float64(step(ydim))) : spacing
    rascrs = Rasters.crs(r)
    m = if !isnothing(manifold)
        manifold
    elseif _isgeographiccrs(rascrs)
        Spherical(; radius=AUTHALIC_RADIUS_M)
    else
        Planar()
    end
    grid = RectilinearGrid(m, P, lookups, steps, rascrs)
    return r, grid
end

# ## The neighborhood vocabulary
#
# `NeighborRings(2)` means rings one and two, matching DGG's cumulative
# `neighbors(grid, cell, 2)` contract.  The count is a plain field: a type
# parameter cost a separate compile per K and bought no inference.

struct NeighborRings
    k::Int
    function NeighborRings(k::Integer=1)
        k >= 1 || throw(ArgumentError("neighbor ring count must be positive"))
        return new(Int(k))
    end
end

# Rectilinear rings are expressed in logical `(dx, dy)` coordinates: positive
# X is east and positive Y is north.  Each square ring starts at north, winds
# counter-clockwise, and outer rings follow inner rings.  Ring one is named for
# kernels that benefit from cardinal fields; larger neighborhoods are ordinary
# ordered positional stencils.

const NORTH_UP_NEIGHBORS = (
    north=(0, 1), northwest=(-1, 1), west=(-1, 0), southwest=(-1, -1),
    south=(0, -1), southeast=(1, -1), east=(1, 0), northeast=(1, 1),
)

function logicalring(k)
    offsets = NTuple{2,Int}[]
    append!(offsets, ((x, k) for x in 0:-1:-k))
    append!(offsets, ((-k, y) for y in (k - 1):-1:-k))
    append!(offsets, ((x, -k) for x in (-k + 1):k))
    append!(offsets, ((k, y) for y in (-k + 1):k))
    append!(offsets, ((x, k) for x in (k - 1):-1:1))
    return Tuple(offsets)
end

logicaloffsets(rings::NeighborRings) =
    rings.k == 1 ? values(NORTH_UP_NEIGHBORS) :
    Tuple(Iterators.flatten(logicalring(k) for k in 1:rings.k))

function storageoffset(grid::RectilinearGrid, (dx, dy))
    xaxis, yaxis = axismap(grid)
    sx, sy = grid.spacing
    return ntuple(2) do axis
        axis == xaxis ? dx * Int(sign(sx)) : dy * Int(sign(sy))
    end
end

function northupstencil(grid::RectilinearGrid, rings::NeighborRings=NeighborRings())
    if rings.k == 1
        return Stencils.NamedStencil(map(o -> storageoffset(grid, o), NORTH_UP_NEIGHBORS))
    else
        return Stencils.Positional(map(o -> storageoffset(grid, o), logicaloffsets(rings)))
    end
end

# Some algorithms need stable, storage-addressable cell identities without
# knowing how a grid represents them.

cellindices(ras, ::RectilinearGrid) = CartesianIndices(axes(ras))

function cellindices(ras, grid::CellGrid)
    return (DGG.SubsetPositionedCell(grid.cells[p], p) for p in eachindex(grid.cells))
end

storagekey(::RectilinearGrid, I) = I
storagekey(::CellGrid, cell) = DGG.cellposition(cell)

# ## Neighbor geometry, hoisted once per call
#
# `neighborgeometry(grid, rings)` materializes per-neighbor distance/bearing
# at the coarsest granularity at which it is invariant: one table for a planar
# rectilinear grid, one table per row of constant latitude for a geographic
# one, cached centroids for a cell grid.  Stencils invokes kernels from a
# KernelAbstractions kernel, so nothing here would be hoisted by the compiler.
#
# Bearing is the tangent-plane bearing on the grid's manifold, clockwise from
# geographic north — on the sphere that is the great-circle initial azimuth.

struct NeighborGeometry{G<:AbstractGridSpec,P}
    grid::G
    rings::NeighborRings
    payload::P
end

function neighborgeometry(grid::RectilinearGrid, rings::NeighborRings=NeighborRings())
    logical = logicaloffsets(rings)
    offsets = map(o -> CartesianIndex(storageoffset(grid, o)), logical)
    return NeighborGeometry(grid, rings, (; offsets, geometry=geometrytable(grid, logical)))
end

function geometrytable(grid::RectilinearGrid{<:Planar}, logical)
    sx, sy = abs.(grid.spacing)
    return map(logical) do (dx, dy)
        (distance=hypot(dx * sx, dy * sy), bearing=mod(atand(dx * sx, dy * sy), 360.0))
    end
end

function geometrytable(grid::RectilinearGrid{<:Spherical}, logical)
    R = grid.manifold.radius
    sx, sy = abs.(grid.spacing)
    return [
        map(logical) do (dx, dy)
            east = dx * deg2rad(sx) * cosd(lat) * R
            north = dy * deg2rad(sy) * R
            (distance=hypot(east, north), bearing=mod(atand(east, north), 360.0))
        end for lat in grid.lookups[2]
    ]
end

geometryat(geom::NeighborGeometry{<:RectilinearGrid{<:Planar}}, I) = geom.payload.geometry
geometryat(geom::NeighborGeometry{<:RectilinearGrid{<:Spherical}}, I) =
    geom.payload.geometry[I[yaxisnum(geom.grid)]]

neighborgeometry(grid::CellGrid, rings::NeighborRings=NeighborRings()) =
    NeighborGeometry(grid, rings,
        [DGG.cell_centroid(grid.levelgrid, c) for c in grid.cells])

# Great-circle initial azimuth is exactly the tangent-plane bearing at the
# from-cell, so both backends satisfy the same bearing contract.
function _edgegeometry(from, to, R)
    central_angle = acos(clamp(sum(from[k] * to[k] for k in 1:3), -1.0, 1.0))
    lon1, lon2 = atan(from[2], from[1]), atan(to[2], to[1])
    lat1, lat2 = asin(clamp(from[3], -1.0, 1.0)), asin(clamp(to[3], -1.0, 1.0))
    delta_lon = lon2 - lon1
    east = sin(delta_lon) * cos(lat2)
    north = cos(lat1) * sin(lat2) - sin(lat1) * cos(lat2) * cos(delta_lon)
    return central_angle * R, mod(rad2deg(atan(east, north)), 360.0)
end

# ## The standalone neighbor query — the traversal verb
#
# Queue-driven algorithms (priority flood, accumulation, HAND) have no map
# call to hoist the geometry for them, so they hoist it themselves and loop:
#
#     geom = neighborgeometry(grid, NeighborRings(1))
#     for I in queue
#         for n in eachneighbor(geom, ras, I) ... end
#     end
#
# The records are lazy over the hoisted cache: `(; index, value, distance,
# bearing)`, identical on every backend.

function eachneighbor(geom::NeighborGeometry{<:RectilinearGrid}, ras, I::CartesianIndex)
    valid = CartesianIndices(ras)
    table = geometryat(geom, I)
    return (
        (; index=I + o, value=ras[I + o], g.distance, g.bearing)
        for (o, g) in zip(geom.payload.offsets, table) if (I + o) in valid
    )
end

function eachneighbor(geom::NeighborGeometry{<:CellGrid}, ras, cell)
    grid = geom.grid
    centroids = geom.payload
    R = manifold(grid).radius
    p0 = DGG.cellposition(cell)
    from = centroids[p0]
    positions = DGG.neighbors(grid.cells, p0, geom.rings.k)
    return (
        begin
            nb = DGG.SubsetPositionedCell(grid.cells[p], p)
            distance, bearing = _edgegeometry(from, centroids[p], R)
            (; index=nb, value=ras[nb], distance, bearing)
        end for p in positions
    )
end

# ## Cell areas
#
# Bulk first: `cellarea(grid)` returns an array-like in storage order whose
# *type* encodes the granularity, so `acc .= cellarea(grid)` is one line on
# every backend and collapses to a constant fill when the area is constant.
# The two tiny lazy arrays below stand in for `FillArrays.Fill` (already a
# package dependency) to keep this PoC standalone.

struct ConstantMatrix{T} <: AbstractMatrix{T}
    value::T
    dims::NTuple{2,Int}
end
Base.size(A::ConstantMatrix) = A.dims
Base.getindex(A::ConstantMatrix, ::Int, ::Int) = A.value
Base.sum(A::ConstantMatrix) = A.value * prod(A.dims) # granularity pays: O(1)

struct RowConstantMatrix{T,V<:AbstractVector{T}} <: AbstractMatrix{T}
    rows::V          # one value per storage index along `rowaxis`
    rowaxis::Int     # the storage axis the values vary along
    dims::NTuple{2,Int}
end
Base.size(A::RowConstantMatrix) = A.dims
Base.getindex(A::RowConstantMatrix, i::Int, j::Int) = A.rows[A.rowaxis == 1 ? i : j]

cellarea(grid::RectilinearGrid{<:Planar}) =
    ConstantMatrix(abs(prod(grid.spacing)), gridsize(grid))

function cellarea(grid::RectilinearGrid{<:Spherical})
    R = grid.manifold.radius
    sx, sy = abs.(grid.spacing)
    areas = [
        R^2 * deg2rad(sx) * abs(sind(lat + sy / 2) - sind(lat - sy / 2))
        for lat in grid.lookups[2]
    ] # exact spherical band area per row of constant latitude
    return RowConstantMatrix(areas, yaxisnum(grid), gridsize(grid))
end

_cellareaof(levelgrid, c) = DGG.cell_area(levelgrid, c) * AUTHALIC_RADIUS_M^2
_cellareaof(levelgrid, c::DGG.Z7Cell) = DGG.IGeo7.cell_area(DGG.rawid(c)) # closed form, m^2

cellarea(grid::CellGrid) = [_cellareaof(grid.levelgrid, c) for c in grid.cells]

# Pointwise for traversal algorithms that touch scattered cells.
cellarea(grid::RectilinearGrid, I) = cellarea(grid)[I]
cellarea(grid::CellGrid, cell) = _cellareaof(grid.levelgrid, DGG.cellid(cell))

# ## Driver 1: mapneighbors — per-neighbor record kernels
#
# Option A nodata: the boundary uses an isbits padval and out-of-bounds
# neighbors are filtered by *index* — `Stencils.indices` returns unclamped
# indices under `Remove`, so the padval never reaches a kernel and the output
# eltype never widens.  Interior nodata (NaN/missing) is the kernel's
# business, matching the package's existing convention.
#
# `Stencils.mapstencil` always threads its kernel; callbacks must be pure.

function mapneighbors(f, ras, grid::RectilinearGrid, rings::NeighborRings=NeighborRings())
    geom = neighborgeometry(grid, rings)
    stencil = northupstencil(grid, rings)
    valid = CartesianIndices(ras)
    # `stencil`, `geom.payload.offsets`, and each geometry table are all built
    # from `logicaloffsets(rings)` in the same order; the zip below relies on
    # that 1:1 alignment.
    return Stencils.mapstencil(stencil, ras, cellindices(ras, grid);
        boundary=Stencils.Remove(zero(eltype(ras)))) do hood, I
        table = geometryat(geom, I)
        neighbors = (
            (; index=CartesianIndex(si), value, g.distance, g.bearing)
            for (value, si, g) in
                zip(Stencils.neighbors(hood), Stencils.indices(stencil, I), table)
            if CartesianIndex(si) in valid
        )
        f(I, Stencils.center(hood), neighbors)
    end
end

# DGG owns cell traversal and output inference; the records ride on the same
# hoisted centroid cache as the standalone query.
function mapneighbors(f, ras::AbstractVector, grid::CellGrid, rings::NeighborRings=NeighborRings())
    geom = neighborgeometry(grid, rings)
    return DGG.mapneighbors(ras; pass=DGG.Neighbors()) do cell, _
        f(cell, ras[cell], eachneighbor(geom, ras, cell))
    end
end

# ## Driver 2: mapwindow — named north-up windows, rectilinear only
#
# Horn-style finite differences want positional values by name, not a record
# stream.  `w.northeast` means geographic northeast in either storage order.
# The window has no meaning on a hex grid, and the error says so.

function mapwindow(f, ras, grid::RectilinearGrid)
    stencil = northupstencil(grid, NeighborRings(1))
    interior = CartesianIndices(map(r -> (first(r) + 1):(last(r) - 1), axes(ras)))
    return Stencils.mapstencil(stencil, ras, cellindices(ras, grid);
        boundary=Stencils.Remove(zero(eltype(ras)))) do hood, I
        I in interior || return NaN
        f(hood, metricspacing(grid, I))
    end
end

mapwindow(f, ras, ::CellGrid) = throw(ArgumentError(
    "windowed drivers require a rectilinear grid; use a neighbor-fit method (e.g. PlaneFit())"))

metricspacing(grid::RectilinearGrid{<:Planar}, I) = abs.(grid.spacing)

function metricspacing(grid::RectilinearGrid{<:Spherical}, I)
    R = grid.manifold.radius
    sx, sy = abs.(grid.spacing)
    lat = grid.lookups[2][I[yaxisnum(grid)]]
    return (deg2rad(sx) * cosd(lat) * R, deg2rad(sy) * R)
end

# ## Algorithms
#
# Family 1: per-neighbor record kernels.

function steepest(value, neighbors)
    best_gradient = 0.0
    best_bearing = NaN
    for neighbor in neighbors
        gradient = (value - neighbor.value) / neighbor.distance
        if gradient > best_gradient
            best_gradient = gradient
            best_bearing = neighbor.bearing
        end
    end
    return best_gradient, best_bearing
end

function _steepest_slope(_, value, neighbors)
    gradient, _ = steepest(value, neighbors)
    return atand(gradient)
end

function _flow_direction(_, value, neighbors)
    _, bearing = steepest(value, neighbors)
    return bearing # clockwise from north; NaN marks a pit or edge outlet
end

steepest_slope(ras, grid::AbstractGridSpec) = mapneighbors(_steepest_slope, ras, grid)
flow_direction(ras, grid::AbstractGridSpec) = mapneighbors(_flow_direction, ras, grid)

# Family 2: windowed derivatives, and the method-dispatch seam.  Horn is one
# *estimator* of the surface gradient and is window-only; PlaneFit estimates
# the same quantity from the records — `distance` and `bearing` place each
# neighbor in the local tangent plane — and works on any grid.

struct Horn end
struct PlaneFit end

slope(ras, grid::AbstractGridSpec; method=defaultmethod(slope, grid)) =
    _slope(method, ras, grid)

defaultmethod(::typeof(slope), ::RectilinearGrid) = Horn()
defaultmethod(::typeof(slope), ::CellGrid) = PlaneFit()

function _horn_slope(w, (sx, sy))
    dzdx = ((w.northeast + 2w.east + w.southeast) -
            (w.northwest + 2w.west + w.southwest)) / (8sx)
    dzdy = ((w.northeast + 2w.north + w.northwest) -
            (w.southeast + 2w.south + w.southwest)) / (8sy)
    return atand(hypot(dzdx, dzdy))
end

function _planefit_slope(_, value, neighbors)
    see = sen = snn = sze = szn = 0.0
    for n in neighbors
        east = n.distance * sind(n.bearing)
        north = n.distance * cosd(n.bearing)
        dz = n.value - value
        see += east * east; sen += east * north; snn += north * north
        sze += dz * east; szn += dz * north
    end
    det = see * snn - sen * sen
    iszero(det) && return NaN
    ddeast = (sze * snn - szn * sen) / det
    ddnorth = (szn * see - sze * sen) / det
    return atand(hypot(ddeast, ddnorth))
end

_slope(::Horn, ras, grid::RectilinearGrid) = mapwindow(_horn_slope, ras, grid)
_slope(::Horn, ras, grid::CellGrid) = throw(ArgumentError(
    "Horn() requires a rectilinear grid; use PlaneFit()"))
_slope(::PlaneFit, ras, grid::AbstractGridSpec) = mapneighbors(_planefit_slope, ras, grid)

# Family 4: a toy D8 accumulation over the bare traversal loop.  One
# implementation serves both backends; `acc .= cellarea(grid)` is the whole
# area story.

function flowaccumulation(ras, grid::AbstractGridSpec)
    geom = neighborgeometry(grid, NeighborRings(1))
    acc = similar(ras, Float64)
    acc .= cellarea(grid)
    cells = vec(collect(cellindices(ras, grid)))
    sort!(cells; by=c -> ras[storagekey(grid, c)], rev=true)
    for c in cells
        z = ras[storagekey(grid, c)]
        best_gradient = 0.0
        best = nothing
        for n in eachneighbor(geom, ras, c)
            gradient = (z - n.value) / n.distance
            if gradient > best_gradient
                best_gradient = gradient
                best = n.index
            end
        end
        isnothing(best) || (acc[storagekey(grid, best)] += acc[storagekey(grid, c)])
    end
    return acc
end

# ## The façade boundary
#
# The resolver's kwarg set is closed and defined in exactly one place: this
# signature.  Julia's own kwarg machinery does the split, so unrecognized
# kwargs — including resolver-side typos — flow to the inner method and die
# there with a normal "unsupported keyword argument" error.  `spatialdims`,
# `spacing`, and `manifold` are reserved names across the public API.

splitspatial(; spatialdims=nothing, spacing=nothing, manifold=nothing, kwargs...) =
    (; spatialdims, spacing, manifold), kwargs

# Output rebuild is the boundary's other half: algorithms below the façade see
# only `(ras, grid) -> data` and never the original input; metadata (name,
# missingval per the package's NaN convention, CRS via the grid) is restored
# here, once.

rebuildoutput(input, grid, data; name) = data # array in, array out

function rebuildoutput(input::Raster, grid, data; name)
    out = data isa Raster ? data : Rasters.rebuild(input; data)
    mv = eltype(out) <: AbstractFloat ? eltype(out)(NaN) : nothing
    return Rasters.rebuild(out; name, missingval=mv)
end

for f in (:steepest_slope, :flow_direction, :slope, :flowaccumulation)
    @eval function $f(input; kwargs...)
        spatial, rest = splitspatial(; kwargs...)
        ras, grid = spatialparts(input; spatial...)
        data = $f(ras, grid; rest...)
        return rebuildoutput(input, grid, data; name=$(QuoteNode(f)))
    end
end

# ## Run the experiment
#
# The same physical plane is stored once as X,Y and once as Y,X.  Y is also
# reverse ordered and the two cell widths differ, so an accidental storage-axis
# assumption is visible.

xs = 0.0:2.0:8.0
ys = 20.0:-5.0:5.0
surface(x, y) = 100.0 - 3.0x

data_xy = [surface(x, y) for x in xs, y in ys]
raster_xy = Raster(data_xy, (X(xs), Y(ys)))
raster_yx = Raster(permutedims(data_xy), (Y(ys), X(xs)))

_, grid_xy = spatialparts(raster_xy)
_, grid_yx = spatialparts(raster_yx)
@assert axismap(grid_xy) == (1, 2)
@assert axismap(grid_yx) == (2, 1)
@assert grid_xy.manifold isa Planar # no CRS -> planar, by construction
@assert collect(cellindices(raster_xy, grid_xy)) == collect(CartesianIndices(raster_xy))

# Named fields have the same geographic meaning in either storage layout.
tagged(x, y) = 100.0x + y
tagged_xy = Raster([tagged(x, y) for x in xs, y in ys], (X(xs), Y(ys)))
tagged_yx = Raster(permutedims(parent(tagged_xy)), (Y(ys), X(xs)))
stencil_xy, stencil_yx = northupstencil(grid_xy), northupstencil(grid_yx)
hood_xy = Stencils.stencil(Stencils.StencilArray(tagged_xy, stencil_xy), (3, 2))
hood_yx = Stencils.stencil(Stencils.StencilArray(tagged_yx, stencil_yx), (2, 3))
@assert all(name -> getproperty(hood_xy, name) == getproperty(hood_yx, name),
    keys(NORTH_UP_NEIGHBORS))
@assert hood_xy.north == tagged(xs[3], ys[1])
@assert hood_xy.east == tagged(xs[4], ys[2])

# The same request grows from the north-up one-ring to cumulative rings one
# and two, without changing the algorithm callback.  Out-of-bounds neighbors
# are dropped by the index filter — no missings involved.
neighborcount(_, _, neighbors) = count(_ -> true, neighbors)
counts1_xy = mapneighbors(neighborcount, raster_xy, grid_xy)
@assert eltype(counts1_xy) == Int # no Union{Int,Missing} widening
@assert parent(counts1_xy)[1, 1] == 3
counts2_xy = mapneighbors(neighborcount, raster_xy, grid_xy, NeighborRings(2))
counts2_yx = mapneighbors(neighborcount, raster_yx, grid_yx, NeighborRings(2))
@assert all(parent(counts2_xy) .>= parent(counts1_xy))
@assert maximum(parent(counts2_xy)) > maximum(parent(counts1_xy))
@assert parent(counts2_xy) == permutedims(parent(counts2_yx))

slope_xy = steepest_slope(raster_xy)
slope_yx = steepest_slope(raster_yx; spatialdims=(X, Y))
direction_xy = flow_direction(raster_xy)
direction_yx = flow_direction(raster_yx)

@assert slope_xy isa Raster
@assert eltype(slope_xy) == Float64 # Option A: no Union{Float64,Missing}
@assert Rasters.name(slope_xy) == :steepest_slope # rebuilt at the boundary
@assert parent(slope_xy) ≈ permutedims(parent(slope_yx))
@assert all(isequal.(parent(direction_xy), permutedims(parent(direction_yx))))
@assert all(d -> isnan(d) || d ≈ 90.0, parent(direction_xy))

# A plain matrix takes the same algorithm path through a synthetic grid, and
# integer eltypes work because the padval is isbits.
matrix_slope = steepest_slope(data_xy; spacing=(2.0, -5.0))
@assert matrix_slope isa Matrix{Float64} # array in, array out
@assert matrix_slope ≈ parent(slope_xy)
int_slope = steepest_slope(Int.(data_xy); spacing=(2.0, -5.0))
@assert int_slope ≈ matrix_slope

# Kwarg splitting: unknown kwargs die on the inner method, reserved kwargs
# stop at the resolver, and unsupported manifolds fail loudly.
bad_kwarg = try steepest_slope(raster_xy; bogus=1); nothing catch e; e end
@assert bad_kwarg isa MethodError
geodesic_err = try spatialparts(raster_xy; manifold=Geodesic()); nothing catch e; e end
@assert geodesic_err isa ArgumentError

# Method dispatch: Horn (window driver) and PlaneFit (record driver) estimate
# the same quantity; on an exact plane both recover it exactly.
horn = slope(raster_xy) # rectilinear default is Horn
@assert all(v -> v ≈ atand(3.0), parent(horn)[2:end-1, 2:end-1])
@assert all(isnan, parent(horn)[1, :]) # window undefined on the border
pf = slope(raster_xy; method=PlaneFit())
@assert all(v -> v ≈ atand(3.0), parent(pf)) # exact even at edges
pf_yx = slope(raster_yx; spatialdims=(X, Y), method=PlaneFit())
@assert parent(pf) ≈ permutedims(parent(pf_yx))

# Cell areas: constant granularity for a planar grid.
ca = cellarea(grid_xy)
@assert ca[3, 2] == 10.0
@assert sum(ca) == 10.0 * length(raster_xy)
@assert cellarea(grid_xy, CartesianIndex(1, 1)) == 10.0

# The traversal family: accumulation over the bare eachneighbor loop.
acc = flowaccumulation(raster_xy)
@assert Rasters.name(acc) == :flowaccumulation
outlets = isnan.(parent(direction_xy))
@assert sum(parent(acc)[outlets]) ≈ sum(cellarea(grid_xy)) # mass conservation
@assert maximum(parent(acc)) ≈ length(xs) * 10.0 # a full row drains east

# A geographic raster resolves to a Spherical manifold; distances, bearings,
# and areas vary by row of constant latitude.
lons = 0.0:1.0:5.0
lats = 60.0:-1.0:55.0
geo_data = [1000.0 - 10.0 * lon for lon in lons, lat in lats]
geo_raster = Raster(geo_data, (X(lons), Y(lats)); crs=EPSG(4326))
_, grid_geo = spatialparts(geo_raster)
@assert grid_geo.manifold isa Spherical

geom_geo = neighborgeometry(grid_geo, NeighborRings(1))
east = findfirst(==(:east), collect(keys(NORTH_UP_NEIGHBORS)))
t60 = geometryat(geom_geo, CartesianIndex(3, 1))
t55 = geometryat(geom_geo, CartesianIndex(3, 6))
@assert t60[east].bearing == 90.0
@assert t60[east].distance ≈ deg2rad(1.0) * cosd(60.0) * AUTHALIC_RADIUS_M
@assert t55[east].distance > t60[east].distance # rows nearer the equator are wider

slope_geo = steepest_slope(geo_raster)
@assert parent(slope_geo)[3, 1] ≈
    atand(10.0 / (deg2rad(1.0) * cosd(60.0) * AUTHALIC_RADIUS_M))
@assert parent(slope_geo)[3, 6] ≈
    atand(10.0 / (deg2rad(1.0) * cosd(55.0) * AUTHALIC_RADIUS_M))
horn_geo = slope(geo_raster)
@assert parent(horn_geo)[3, 2] ≈
    atand(10.0 / (deg2rad(1.0) * cosd(59.0) * AUTHALIC_RADIUS_M))

ca_geo = cellarea(grid_geo)
@assert ca_geo[1, 1] ≈ AUTHALIC_RADIUS_M^2 * deg2rad(1.0) * (sind(60.5) - sind(59.5))
@assert ca_geo[1, 6] > ca_geo[1, 1]

# Finally, a real DGG raster takes the same paths.  Elevation rises with the
# centroid's Z coordinate, giving most cells a downhill neighbor.
level = 2
dgg = DGG.levelgrid(DGG.IGeo7System(), level)
cell_lookup = DGG.CellLookup(dgg)
cell_values = [10_000.0 * DGG.cell_centroid(dgg, cell)[3] for cell in cell_lookup]
cell_raster = Raster(cell_values, (DGG.Cells(cell_lookup),))

_, cell_grid = spatialparts(cell_raster; spatialdims=DGG.Cells)
@assert cell_grid isa CellGrid
@assert cell_grid.cells === cell_lookup.cells
@assert manifold(cell_grid) isa Spherical

cell_index = first(cellindices(cell_raster, cell_grid))
@assert cell_index isa DGG.SubsetPositionedCell
@assert cell_raster[cell_index] == first(cell_values)

cell_counts2 = mapneighbors(neighborcount, cell_raster, cell_grid, NeighborRings(2))
@assert parent(cell_counts2)[1] == length(DGG.neighbors(cell_lookup, 1, 2))

cell_areas = cellarea(cell_grid)
@assert sum(cell_areas) ≈ 4π * AUTHALIC_RADIUS_M^2 # IGeo7 tiles the sphere exactly
@assert cellarea(cell_grid, cell_index) == cell_areas[1]

cell_slope = steepest_slope(cell_raster)
cell_direction = flow_direction(cell_raster)
@assert cell_slope isa Raster
@assert all(>=(0.0), parent(cell_slope))
@assert any(isfinite, parent(cell_direction))
@assert all(d -> isnan(d) || 0.0 <= d < 360.0, parent(cell_direction))

pf_cells = slope(cell_raster) # CellGrid default is PlaneFit
@assert all(isfinite, parent(pf_cells))
horn_err = try slope(cell_raster; method=Horn()); nothing catch e; e end
@assert horn_err isa ArgumentError

cell_acc = flowaccumulation(cell_raster)
cell_outlets = isnan.(parent(cell_direction))
@assert sum(parent(cell_acc)[cell_outlets]) ≈ sum(cell_areas) # conservation on the sphere

println("PoC v2 passed: manifolds, split kwargs, three drivers, and cell areas " *
        "agree across both axis orders and the CellGrid backend.")
